//
//  ListModels.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import OpenWeatherMapKit

enum List {
    // MARK: Use cases
    enum Forecasts {
        struct Request {
            var cities = ["Paris", "Nantes", "Angers", "Saumur"]
        }

        struct Response {
            var forecasts: [String: ForecastItem]
        }

        struct ViewModel {
            struct DisplayedForecast {
                var city: String
                var weather: String?
                var temperature: String

                var description: String {
                    return String(format: "%@ : %@ (%@)", city, weather ?? "", temperature)
                }

                init(city: String, forecast: ForecastItem) {
                    self.city = city.capitalized
                    self.weather = forecast.weather.first?.description.capitalized
                    self.temperature = String(format: "%.0f°C", forecast.main.celsius.currentTemp)
                }
            }

            var displayedForecasts: [DisplayedForecast]
        }
    }
}
