//
//  ListPresenter.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentNavigationBarTitle()
    func presentFetchedForecasts(response: List.Forecasts.Response)
}

class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?

    func presentNavigationBarTitle() {
        let viewModel = List.NavigationBar.ViewModel(title: "Meteo")
        viewController?.displayNavigationBarTitle(viewModel: viewModel)
    }

    func presentFetchedForecasts(response: List.Forecasts.Response) {
        var displayedForecasts = [List.Forecasts.ViewModel.DisplayedForecast]()
        response.forecasts.keys.forEach { city in
            guard let forecast = response.forecasts[city] else { return }

            let displayedForecast = List.Forecasts.ViewModel.DisplayedForecast(city: city, forecast: forecast)
            displayedForecasts.append(displayedForecast)
        }

        let viewModel = List.Forecasts.ViewModel(displayedForecasts: displayedForecasts.sorted(by: { $0.city < $1.city }))
        viewController?.displayCurrentForecasts(viewModel: viewModel)
    }
}
