//
//  ListWorker.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import OpenWeatherMapKit

class ListWorker {
    var forecastsStore: ForecastsStoreProtocol

    init(forecastsStore: ForecastsStoreProtocol) {
      self.forecastsStore = forecastsStore
    }

    func fetchCurrentForecasts(for city: String, completionHandler: @escaping (ForecastItem?, Error?) -> Void) {
        forecastsStore.fetchCurrentForecast(for: city) { forecast, error in
            completionHandler(forecast, error)
        }
    }
}
