//
//  DetailsPresenter.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentNavigationBarTitle(with title: String)
    func presentForecasts(response: Details.Forecasts.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?

    func presentNavigationBarTitle(with title: String) {
        let viewModel = Details.NavigationBar.ViewModel(title: title)
        viewController?.displayNavigationBarTitle(viewModel: viewModel)
    }

    func presentForecasts(response: Details.Forecasts.Response) {
        var displayedForecasts = [Details.Forecasts.ViewModel.DisplayedForecast]()
        response.forecasts.list.forEach { forecast in
            if let date = forecast.dt_txt, date.hasSuffix("12:00:00") { // Only keeping midday forecasts
                let displayedForecast = Details.Forecasts.ViewModel.DisplayedForecast(forecast: forecast)
                displayedForecasts.append(displayedForecast)
            }
        }

        let viewModel = Details.Forecasts.ViewModel(displayedForecasts: displayedForecasts)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
