//
//  DetailsInteractor.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func setNavigationBarTitle()
    func fetchWeekForecasts(request: Details.Forecasts.Request)
}

protocol DetailsDataStore {
    var city: String? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var city: String?

    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?

    func setNavigationBarTitle() {
        if let city = city {
            presenter?.presentNavigationBarTitle(with: city)
        }
    }

    func fetchWeekForecasts(request: Details.Forecasts.Request) {
        guard let city = city else { return }

        worker = DetailsWorker(forecastsStore: OpenWeatherAPI())

        worker?.fetchWeekForecasts(for: city, completionHandler: { [weak self] forecasts, error in
            guard let forecasts = forecasts else { return }

            let response = Details.Forecasts.Response(city: city, forecasts: forecasts)
            self?.presenter?.presentForecasts(response: response)
        })
    }
}
