//
//  DetailsInteractor.swift
//  Meteo
//
//  Created by Fromage Charley on 05/10/2019.
//  Copyright (c) 2019 Fromage Charley. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func fetchWeekForecasts(request: Details.Forecasts.Request)
}

protocol DetailsDataStore {
    var name: String { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var name: String = "Details"

    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?

    func fetchWeekForecasts(request: Details.Forecasts.Request) {
        worker = DetailsWorker(forecastsStore: OpenWeatherAPI())

        worker?.fetchWeekForecasts(for: request.city, completionHandler: { [weak self] forecasts, error in
            guard let forecasts = forecasts else { return }

            let response = Details.Forecasts.Response(forecasts: forecasts)
            self?.presenter?.presentForecasts(response: response)
        })
    }
}
